In [ ]:
# importing file named DOS_Wednesday-no-metadata.parquet
from google.colab import files
uploaded = files.upload()

Saving DoS-Wednesday-no-metadata.parquet to DoS-Wednesday-no-metadata.parquet

In [ ]:
# importing file named Benign-Monday-no-metadata.parquet
from google.colab import files
normal_day = files.upload()

Saving Benign-Monday-no-metadata.parquet to Benign-Monday-no-metadata.parquet

In [ ]:
# necessary installation
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [ ]:
# Get Monday and Wednesday parquet values as monday_df and wednesday_df respectively
import pandas as pd

monday_df = pd.read_parquet("/content/Benign-Monday-no-metadata.parquet")
wednesday_df = pd.read_parquet("/content/DoS-Wednesday-no-metadata.parquet")

In [ ]:
# Get first 100K values
monday_df.head(100000)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,4,2,0,12,0,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1,2,0,12,0,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,3,2,0,12,0,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1,2,0,12,0,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,609,7,4,484,414,233,0,69.142860,111.967896,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,6,187435,10,5,646,687,405,0,64.599998,128.033157,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
99996,6,224570,14,9,840,5748,357,0,60.000000,113.324585,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
99997,6,243657,17,13,2289,8893,1368,0,134.647064,357.012604,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
99998,6,248729,13,6,1424,2890,901,0,109.538460,249.485001,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
99999,6,65,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [ ]:
# To understand Datastructure
monday_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458831 entries, 0 to 458830
Data columns (total 78 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Protocol                  458831 non-null  int8
 1   Flow Duration             458831 non-null  int32
 2   Total Fwd Packets         458831 non-null  int32
 3   Total Backward Packets    458831 non-null  int32
 4   Fwd Packets Length Total  458831 non-null  int32
 5   Bwd Packets Length Total  458831 non-null  int32
 6   Fwd Packet Length Max     458831 non-null  int16
 7   Fwd Packet Length Min     458831 non-null  int16
 8   Fwd Packet Length Mean    458831 non-null  float32
 9   Fwd Packet Length Std     458831 non-null  float32
 10  Bwd Packet Length Max     458831 non-null  int16
 11  Bwd Packet Length Min     458831 non-null  int16
 12  Bwd Packet Length Mean    458831 non-null  float32
 13  Bwd Packet Length Std     458831 non-null  float32
 14  Flow Bytes/s              458831 non-null  float64
 15  Flow Packets/s            458831 non-null  float64
 16  Flow IAT Mean             458831 non-null  float32
 17  Flow IAT Std              458831 non-null  float32
 18  Flow IAT Max              458831 non-null  int32
 19  Flow IAT Min              458831 non-null  int32
 20  Fwd IAT Total             458831 non-null  int32
 21  Fwd IAT Mean              458831 non-null  float32
 22  Fwd IAT Std               458831 non-null  float32
 23  Fwd IAT Max               458831 non-null  int32
 24  Fwd IAT Min               458831 non-null  int32
 25  Bwd IAT Total             458831 non-null  int32
 26  Bwd IAT Mean              458831 non-null  float32
 27  Bwd IAT Std               458831 non-null  float32
 28  Bwd IAT Max               458831 non-null  int32
 29  Bwd IAT Min               458831 non-null  int32
 30  Fwd PSH Flags             458831 non-null  int8
 31  Bwd PSH Flags             458831 non-null  int8
 32  Fwd URG Flags             458831 non-null  int8
 33  Bwd URG Flags             458831 non-null  int8
 34  Fwd Header Length         458831 non-null  int32
 35  Bwd Header Length         458831 non-null  int32
 36  Fwd Packets/s             458831 non-null  float32
 37  Bwd Packets/s             458831 non-null  float32
 38  Packet Length Min         458831 non-null  int16
 39  Packet Length Max         458831 non-null  int16
 40  Packet Length Mean        458831 non-null  float32
 41  Packet Length Std         458831 non-null  float32
 42  Packet Length Variance    458831 non-null  float32
 43  FIN Flag Count            458831 non-null  int8
 44  SYN Flag Count            458831 non-null  int8
 45  RST Flag Count            458831 non-null  int8
 46  PSH Flag Count            458831 non-null  int8
 47  ACK Flag Count            458831 non-null  int8
 48  URG Flag Count            458831 non-null  int8
 49  CWE Flag Count            458831 non-null  int8
 50  ECE Flag Count            458831 non-null  int8
 51  Down/Up Ratio             458831 non-null  int8
 52  Avg Packet Size           458831 non-null  float32
 53  Avg Fwd Segment Size      458831 non-null  float32
 54  Avg Bwd Segment Size      458831 non-null  float32
 55  Fwd Avg Bytes/Bulk        458831 non-null  int8
 56  Fwd Avg Packets/Bulk      458831 non-null  int8
 57  Fwd Avg Bulk Rate         458831 non-null  int8
 58  Bwd Avg Bytes/Bulk        458831 non-null  int8
 59  Bwd Avg Packets/Bulk      458831 non-null  int8
 60  Bwd Avg Bulk Rate         458831 non-null  int8
 61  Subflow Fwd Packets       458831 non-null  int32
 62  Subflow Fwd Bytes         458831 non-null  int32
 63  Subflow Bwd Packets       458831 non-null  int32
 64  Subflow Bwd Bytes         458831 non-null  int32
 65  Init Fwd Win Bytes        458831 non-null  int32
 66  Init Bwd Win Bytes        458831 non-null  int32
 67  Fwd Act Data Packets      458831 non-null  int32
 68  Fwd Seg Size Min          458831 non-null  int32
 69  Active Mean               458831 non-null  float32
 70  Active Std                458831 non-null  float32
 71  Active Max                458831 non-null  int32
 72  Active Min                458831 non-null  int32
 73  Idle Mean                 458831 non-null  float32
 74  Idle Std                  458831 non-null  float32
 75  Idle Max                  458831 non-null  int32
 76  Idle Min                  458831 non-null  int32
 77  Label                     458831 non-null  category
dtypes: category(1), float32(22), float64(2), int16(6), int32(27), int8(20)
memory usage: 107.2 MB

In [ ]:
#Knowing the dimension of the dataframe
monday_df.shape

(458831, 78)

In [ ]:
#checking for missing values
monday_df.isna().sum()

Protocol                    0
Flow Duration               0
Total Fwd Packets           0
Total Backward Packets      0
Fwd Packets Length Total    0
                           ..
Idle Mean                   0
Idle Std                    0
Idle Max                    0
Idle Min                    0
Label                       0
Length: 78, dtype: int64

In [ ]:
# to label each attack type
monday_df['Label'].value_counts()

Label
Benign    458831
Name: count, dtype: int64

In [ ]:
# Number of rows before dropping duplicates
before = monday_df.shape[0]

# Drop duplicates
monday_df = monday_df.drop_duplicates()

# Number of rows after dropping duplicates
after = monday_df.shape[0]

# Number of duplicates dropped
print("Duplicates dropped:", before - after)

Duplicates dropped: 0

In [ ]:
# Get first 100K values
wednesday_df.head(100000)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,38308,1,1,6,6,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,479,11,5,172,326,79,0,15.636364,31.449238,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,1095,10,6,3150,3150,1575,0,315.000000,632.561646,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,15206,17,12,3452,6660,1313,0,203.058823,425.778473,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,1092,9,6,3150,3152,1575,0,350.000000,694.509705,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,6,99423523,5,6,380,11595,368,0,76.000000,163.260529,...,20,12855.0,0.0,12855,12855,99300000.0,0.0,99300000,99300000,DoS Hulk
99996,6,99425736,7,6,360,11595,354,0,51.428570,133.440201,...,20,1994.0,0.0,1994,1994,99300000.0,0.0,99300000,99300000,DoS Hulk
99997,6,99423079,5,7,375,11595,363,0,75.000000,161.024841,...,20,13036.0,0.0,13036,13036,99200000.0,0.0,99200000,99200000,DoS Hulk
99998,6,99421917,6,8,377,11595,359,0,62.833332,145.121216,...,20,13001.0,0.0,13001,13001,99200000.0,0.0,99200000,99200000,DoS Hulk
99999,6,99423905,8,6,302,11595,302,0,37.750000,106.773125,...,32,1015.0,0.0,1015,1015,99300000.0,0.0,99300000,99300000,DoS Hulk

In [ ]:
# To understand Datastructure
wednesday_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584991 entries, 0 to 584990
Data columns (total 78 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Protocol                  584991 non-null  int8
 1   Flow Duration             584991 non-null  int32
 2   Total Fwd Packets         584991 non-null  int32
 3   Total Backward Packets    584991 non-null  int32
 4   Fwd Packets Length Total  584991 non-null  int32
 5   Bwd Packets Length Total  584991 non-null  int32
 6   Fwd Packet Length Max     584991 non-null  int16
 7   Fwd Packet Length Min     584991 non-null  int16
 8   Fwd Packet Length Mean    584991 non-null  float32
 9   Fwd Packet Length Std     584991 non-null  float32
 10  Bwd Packet Length Max     584991 non-null  int16
 11  Bwd Packet Length Min     584991 non-null  int16
 12  Bwd Packet Length Mean    584991 non-null  float32
 13  Bwd Packet Length Std     584991 non-null  float32
 14  Flow Bytes/s              584991 non-null  float64
 15  Flow Packets/s            584991 non-null  float64
 16  Flow IAT Mean             584991 non-null  float32
 17  Flow IAT Std              584991 non-null  float32
 18  Flow IAT Max              584991 non-null  int32
 19  Flow IAT Min              584991 non-null  int32
 20  Fwd IAT Total             584991 non-null  int32
 21  Fwd IAT Mean              584991 non-null  float32
 22  Fwd IAT Std               584991 non-null  float32
 23  Fwd IAT Max               584991 non-null  int32
 24  Fwd IAT Min               584991 non-null  int32
 25  Bwd IAT Total             584991 non-null  int32
 26  Bwd IAT Mean              584991 non-null  float32
 27  Bwd IAT Std               584991 non-null  float32
 28  Bwd IAT Max               584991 non-null  int32
 29  Bwd IAT Min               584991 non-null  int32
 30  Fwd PSH Flags             584991 non-null  int8
 31  Bwd PSH Flags             584991 non-null  int8
 32  Fwd URG Flags             584991 non-null  int8
 33  Bwd URG Flags             584991 non-null  int8
 34  Fwd Header Length         584991 non-null  int32
 35  Bwd Header Length         584991 non-null  int32
 36  Fwd Packets/s             584991 non-null  float32
 37  Bwd Packets/s             584991 non-null  float32
 38  Packet Length Min         584991 non-null  int16
 39  Packet Length Max         584991 non-null  int16
 40  Packet Length Mean        584991 non-null  float32
 41  Packet Length Std         584991 non-null  float32
 42  Packet Length Variance    584991 non-null  float32
 43  FIN Flag Count            584991 non-null  int8
 44  SYN Flag Count            584991 non-null  int8
 45  RST Flag Count            584991 non-null  int8
 46  PSH Flag Count            584991 non-null  int8
 47  ACK Flag Count            584991 non-null  int8
 48  URG Flag Count            584991 non-null  int8
 49  CWE Flag Count            584991 non-null  int8
 50  ECE Flag Count            584991 non-null  int8
 51  Down/Up Ratio             584991 non-null  int8
 52  Avg Packet Size           584991 non-null  float32
 53  Avg Fwd Segment Size      584991 non-null  float32
 54  Avg Bwd Segment Size      584991 non-null  float32
 55  Fwd Avg Bytes/Bulk        584991 non-null  int8
 56  Fwd Avg Packets/Bulk      584991 non-null  int8
 57  Fwd Avg Bulk Rate         584991 non-null  int8
 58  Bwd Avg Bytes/Bulk        584991 non-null  int8
 59  Bwd Avg Packets/Bulk      584991 non-null  int8
 60  Bwd Avg Bulk Rate         584991 non-null  int8
 61  Subflow Fwd Packets       584991 non-null  int32
 62  Subflow Fwd Bytes         584991 non-null  int32
 63  Subflow Bwd Packets       584991 non-null  int32
 64  Subflow Bwd Bytes         584991 non-null  int32
 65  Init Fwd Win Bytes        584991 non-null  int32
 66  Init Bwd Win Bytes        584991 non-null  int32
 67  Fwd Act Data Packets      584991 non-null  int32
 68  Fwd Seg Size Min          584991 non-null  int8
 69  Active Mean               584991 non-null  float32
 70  Active Std                584991 non-null  float32
 71  Active Max                584991 non-null  int32
 72  Active Min                584991 non-null  int32
 73  Idle Mean                 584991 non-null  float32
 74  Idle Std                  584991 non-null  float32
 75  Idle Max                  584991 non-null  int32
 76  Idle Min                  584991 non-null  int32
 77  Label                     584991 non-null  category
dtypes: category(1), float32(22), float64(2), int16(6), int32(26), int8(21)
memory usage: 135.0 MB

In [ ]:
##Knowing the dimension of the dataframe
wednesday_df.shape

(584991, 78)

In [ ]:
# checking for null values
wednesday_df.isna().sum()

Protocol                    0
Flow Duration               0
Total Fwd Packets           0
Total Backward Packets      0
Fwd Packets Length Total    0
                           ..
Idle Mean                   0
Idle Std                    0
Idle Max                    0
Idle Min                    0
Label                       0
Length: 78, dtype: int64

In [ ]:
# to label each attack type
wednesday_df['Label'].value_counts()

Label
Benign              391235
DoS Hulk            172846
DoS GoldenEye        10286
DoS slowloris         5385
DoS Slowhttptest      5228
Heartbleed              11
Name: count, dtype: int64

In [ ]:
# Number of rows before dropping duplicates
before = wednesday_df.shape[0]

# Drop duplicates
wednesday_df= wednesday_df.drop_duplicates()

# Number of rows after dropping duplicates
after = wednesday_df.shape[0]

# Number of duplicates dropped
print("Duplicates dropped:", before - after)

Duplicates dropped: 0

In [ ]:
# check made to make sure if the both files have same column name at the same position

monday_col_list = list(monday_df.columns.values)
wednesday_col_list = list(wednesday_df.columns.values)

mon_col_count = len(monday_col_list)
wed_col_count = len(wednesday_col_list)

print("Mon col count", mon_col_count)
print("Wed col count", wed_col_count)

matched_col_count = 0

# checking if both list have same number of columns
if wed_col_count == mon_col_count:

  # checking column names in both list with their index
  for i in range(wed_col_count):
    if wednesday_col_list[i] == monday_col_list[i]:
      matched_col_count += 1
else:
  print("column count not same")

Mon col count 78
Wed col count 78
Both lists are identical: True

In [ ]:
"""
Check if the if both lists are identical, if yes,
Change column names of any one list in camelcase (i.e) all lowercase letters
with spaces replaced with underscore and store it as final_col_list
"""
final_col_list = []
identical = matched_col_count == wed_col_count and matched_col_count == mon_col_count
print("Both lists are identical:", identical)

if identical:
  final_col_list = monday_df.columns.str.replace(' ', '_').str.lower()
  print(final_col_list)

Both lists are identical: True
Index(['protocol', 'flow_duration', 'total_fwd_packets',
       'total_backward_packets', 'fwd_packets_length_total',
       'bwd_packets_length_total', 'fwd_packet_length_max',
       'fwd_packet_length_min', 'fwd_packet_length_mean',
       'fwd_packet_length_std', 'bwd_packet_length_max',
       'bwd_packet_length_min', 'bwd_packet_length_mean',
       'bwd_packet_length_std', 'flow_bytes/s', 'flow_packets/s',
       'flow_iat_mean', 'flow_iat_std', 'flow_iat_max', 'flow_iat_min',
       'fwd_iat_total', 'fwd_iat_mean', 'fwd_iat_std', 'fwd_iat_max',
       'fwd_iat_min', 'bwd_iat_total', 'bwd_iat_mean', 'bwd_iat_std',
       'bwd_iat_max', 'bwd_iat_min', 'fwd_psh_flags', 'bwd_psh_flags',
       'fwd_urg_flags', 'bwd_urg_flags', 'fwd_header_length',
       'bwd_header_length', 'fwd_packets/s', 'bwd_packets/s',
       'packet_length_min', 'packet_length_max', 'packet_length_mean',
       'packet_length_std', 'packet_length_variance', 'fin_flag_count',
       'syn_flag_count', 'rst_flag_count', 'psh_flag_count', 'ack_flag_count',
       'urg_flag_count', 'cwe_flag_count', 'ece_flag_count', 'down/up_ratio',
       'avg_packet_size', 'avg_fwd_segment_size', 'avg_bwd_segment_size',
       'fwd_avg_bytes/bulk', 'fwd_avg_packets/bulk', 'fwd_avg_bulk_rate',
       'bwd_avg_bytes/bulk', 'bwd_avg_packets/bulk', 'bwd_avg_bulk_rate',
       'subflow_fwd_packets', 'subflow_fwd_bytes', 'subflow_bwd_packets',
       'subflow_bwd_bytes', 'init_fwd_win_bytes', 'init_bwd_win_bytes',
       'fwd_act_data_packets', 'fwd_seg_size_min', 'active_mean', 'active_std',
       'active_max', 'active_min', 'idle_mean', 'idle_std', 'idle_max',
       'idle_min', 'label'],
      dtype='object')

In [ ]:
# concatenating monday_df and wednesday_df (row-wise)

if identical:
  df_combined = pd.concat([monday_df.head(100000),wednesday_df.head(100000)], ignore_index=True)

In [ ]:
# To know the structure of dataset
df_combined.shape

(200000, 78)

In [ ]:
# detailed information of the combined-dataset
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 78 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Protocol                  200000 non-null  int8
 1   Flow Duration             200000 non-null  int32
 2   Total Fwd Packets         200000 non-null  int32
 3   Total Backward Packets    200000 non-null  int32
 4   Fwd Packets Length Total  200000 non-null  int32
 5   Bwd Packets Length Total  200000 non-null  int32
 6   Fwd Packet Length Max     200000 non-null  int16
 7   Fwd Packet Length Min     200000 non-null  int16
 8   Fwd Packet Length Mean    200000 non-null  float32
 9   Fwd Packet Length Std     200000 non-null  float32
 10  Bwd Packet Length Max     200000 non-null  int16
 11  Bwd Packet Length Min     200000 non-null  int16
 12  Bwd Packet Length Mean    200000 non-null  float32
 13  Bwd Packet Length Std     200000 non-null  float32
 14  Flow Bytes/s              200000 non-null  float64
 15  Flow Packets/s            200000 non-null  float64
 16  Flow IAT Mean             200000 non-null  float32
 17  Flow IAT Std              200000 non-null  float32
 18  Flow IAT Max              200000 non-null  int32
 19  Flow IAT Min              200000 non-null  int32
 20  Fwd IAT Total             200000 non-null  int32
 21  Fwd IAT Mean              200000 non-null  float32
 22  Fwd IAT Std               200000 non-null  float32
 23  Fwd IAT Max               200000 non-null  int32
 24  Fwd IAT Min               200000 non-null  int32
 25  Bwd IAT Total             200000 non-null  int32
 26  Bwd IAT Mean              200000 non-null  float32
 27  Bwd IAT Std               200000 non-null  float32
 28  Bwd IAT Max               200000 non-null  int32
 29  Bwd IAT Min               200000 non-null  int32
 30  Fwd PSH Flags             200000 non-null  int8
 31  Bwd PSH Flags             200000 non-null  int8
 32  Fwd URG Flags             200000 non-null  int8
 33  Bwd URG Flags             200000 non-null  int8
 34  Fwd Header Length         200000 non-null  int32
 35  Bwd Header Length         200000 non-null  int32
 36  Fwd Packets/s             200000 non-null  float32
 37  Bwd Packets/s             200000 non-null  float32
 38  Packet Length Min         200000 non-null  int16
 39  Packet Length Max         200000 non-null  int16
 40  Packet Length Mean        200000 non-null  float32
 41  Packet Length Std         200000 non-null  float32
 42  Packet Length Variance    200000 non-null  float32
 43  FIN Flag Count            200000 non-null  int8
 44  SYN Flag Count            200000 non-null  int8
 45  RST Flag Count            200000 non-null  int8
 46  PSH Flag Count            200000 non-null  int8
 47  ACK Flag Count            200000 non-null  int8
 48  URG Flag Count            200000 non-null  int8
 49  CWE Flag Count            200000 non-null  int8
 50  ECE Flag Count            200000 non-null  int8
 51  Down/Up Ratio             200000 non-null  int8
 52  Avg Packet Size           200000 non-null  float32
 53  Avg Fwd Segment Size      200000 non-null  float32
 54  Avg Bwd Segment Size      200000 non-null  float32
 55  Fwd Avg Bytes/Bulk        200000 non-null  int8
 56  Fwd Avg Packets/Bulk      200000 non-null  int8
 57  Fwd Avg Bulk Rate         200000 non-null  int8
 58  Bwd Avg Bytes/Bulk        200000 non-null  int8
 59  Bwd Avg Packets/Bulk      200000 non-null  int8
 60  Bwd Avg Bulk Rate         200000 non-null  int8
 61  Subflow Fwd Packets       200000 non-null  int32
 62  Subflow Fwd Bytes         200000 non-null  int32
 63  Subflow Bwd Packets       200000 non-null  int32
 64  Subflow Bwd Bytes         200000 non-null  int32
 65  Init Fwd Win Bytes        200000 non-null  int32
 66  Init Bwd Win Bytes        200000 non-null  int32
 67  Fwd Act Data Packets      200000 non-null  int32
 68  Fwd Seg Size Min          200000 non-null  int32
 69  Active Mean               200000 non-null  float32
 70  Active Std                200000 non-null  float32
 71  Active Max                200000 non-null  int32
 72  Active Min                200000 non-null  int32
 73  Idle Mean                 200000 non-null  float32
 74  Idle Std                  200000 non-null  float32
 75  Idle Max                  200000 non-null  int32
 76  Idle Min                  200000 non-null  int32
 77  Label                     200000 non-null  object
dtypes: float32(22), float64(2), int16(6), int32(27), int8(20), object(1)
memory usage: 48.1+ MB

In [ ]:
# checking for the null values
df_combined.isna().sum()

Protocol                    0
Flow Duration               0
Total Fwd Packets           0
Total Backward Packets      0
Fwd Packets Length Total    0
                           ..
Idle Mean                   0
Idle Std                    0
Idle Max                    0
Idle Min                    0
Label                       0
Length: 78, dtype: int64

In [ ]:
df_combined.to_csv('/content/combined_200k.csv', index=False)